#!/usr/bin/env python3
"""
Complete Workflow: Fetch News → Create Clips → Upload to YouTube

This script demonstrates the complete automation workflow:
1. Fetch viral news/tech videos
2. Create short clips from them
3. Upload clips to YouTube

Prerequisites:
- YouTube authentication (see YOUTUBE_UPLOAD_SKILL.md)
- yt-dlp installed: pip install yt-dlp
- ffmpeg installed (for video processing)
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from src.skills.news_extractor.skill import NewsExtractorSkill
from src.skills.youtube_upload.skill import YouTubeUploadSkill
from src.integrations.youtube import YouTubeProvider
from src.agent.context import Context


def main():
    print("=" * 70)
    print("COMPLETE WORKFLOW: NEWS → CLIPS → YOUTUBE")
    print("=" * 70)
    
    # Initialize skills
    context = Context()
    news_skill = NewsExtractorSkill()
    youtube_provider = YouTubeProvider()
    youtube_skill = YouTubeUploadSkill(youtube_provider)
    
    # Check YouTube authentication
    auth_result = youtube_skill.execute("check_auth", {}, context)
    print(f"\n{auth_result.message}\n")
    
    if not youtube_provider.is_authenticated():
        print("⚠️  Please authenticate with YouTube first!")
        print("See YOUTUBE_UPLOAD_SKILL.md for setup instructions.")
        return
    
    # Step 1: Fetch viral tech videos
    print("=" * 70)
    print("STEP 1: Fetching Viral Tech Videos")
    print("=" * 70)
    
    fetch_result = news_skill.execute("fetch_tech", {
        "max_results": 3
    }, context)
    
    if not fetch_result.success:
        print(f"❌ Failed to fetch videos: {fetch_result.message}")
        return
    
    print(fetch_result.message)
    videos = fetch_result.data.get("videos", [])
    
    if not videos:
        print("❌ No videos found")
        return
    
    # Step 2: Create clips
    print("\n" + "=" * 70)
    print("STEP 2: Creating Video Clips")
    print("=" * 70)
    print("\nℹ️  To create clips, you need to:")
    print("1. Run: python src/skills/NewsExtractor/clipper.py")
    print("2. Or run: python src/skills/NewsExtractor/videoClipper.py")
    print("3. Choose videos from the list above")
    print("4. Clips will be saved to shorts_from_youtube/ or output_videos/")
    
    input("\nPress Enter after creating clips to continue with upload...")
    
    # Step 3: Check for available clips
    print("\n" + "=" * 70)
    print("STEP 3: Scanning for Clips")
    print("=" * 70)
    
    possible_dirs = [
        Path("src/skills/NewsExtractor/shorts_from_youtube"),
        Path("src/skills/NewsExtractor/output_videos"),
    ]
    
    all_clips = []
    for dir_path in possible_dirs:
        if dir_path.exists():
            clips = sorted(dir_path.glob("*.mp4"))
            all_clips.extend([(clip, dir_path.name) for clip in clips])
    
    if not all_clips:
        print("❌ No clips found. Please create clips first using clipper.py")
        return
    
    print(f"\n✅ Found {len(all_clips)} clip(s):")
    for i, (clip, dir_name) in enumerate(all_clips[:10]):  # Show first 10
        size_mb = clip.stat().st_size / (1024 * 1024)
        print(f"  {i}. {clip.name} ({size_mb:.1f} MB) - {dir_name}/")
    
    # Step 4: Upload clips to YouTube
    print("\n" + "=" * 70)
    print("STEP 4: Uploading Clips to YouTube")
    print("=" * 70)
    
    # Ask how many to upload
    try:
        num_to_upload = int(input(f"\nHow many clips to upload? (1-{min(len(all_clips), 6)}): ") or "3")
        num_to_upload = max(1, min(num_to_upload, len(all_clips), 6))  # Max 6 per day
    except ValueError:
        num_to_upload = 3
    
    print(f"\n📤 Uploading {num_to_upload} clip(s)...\n")
    
    uploaded = []
    failed = []
    
    for i in range(num_to_upload):
        clip_path, dir_name = all_clips[i]
        
        print(f"\n[{i+1}/{num_to_upload}] Uploading: {clip_path.name}")
        print("-" * 50)
        
        # Auto-generate title from clip name and context
        title = f"Viral Tech Clip #{i+1} - {clip_path.stem}"
        
        description = (
            "🔥 Viral tech news clip!\n\n"
            "Auto-generated by LightClaw Agent\n"
            f"Source: {dir_name}\n\n"
            "#shorts #tech #viral #trending"
        )
        
        upload_result = youtube_skill.execute("upload", {
            "video_path": str(clip_path),
            "title": title[:100],  # Max 100 chars
            "description": description,
            "tags": ["shorts", "tech", "viral", "trending", "news"],
            "privacy": "unlisted",  # Start with unlisted
            "category_id": "28",  # Science & Technology
        }, context)
        
        if upload_result.success:
            print(f"✅ Success!")
            print(f"   URL: {upload_result.data['url']}")
            uploaded.append({
                "clip": clip_path.name,
                "url": upload_result.data['url'],
                "video_id": upload_result.data['id']
            })
        else:
            print(f"❌ Failed: {upload_result.message}")
            failed.append(clip_path.name)
    
    # Step 5: Summary
    print("\n" + "=" * 70)
    print("WORKFLOW COMPLETE!")
    print("=" * 70)
    
    print(f"\n📊 Summary:")
    print(f"   ✅ Uploaded: {len(uploaded)}")
    print(f"   ❌ Failed: {len(failed)}")
    
    if uploaded:
        print(f"\n📹 Uploaded videos:")
        for item in uploaded:
            print(f"   • {item['clip']}")
            print(f"     {item['url']}")
    
    if failed:
        print(f"\n⚠️  Failed clips:")
        for clip_name in failed:
            print(f"   • {clip_name}")
    
    print("\n💡 Tips:")
    print("   • Videos are uploaded as 'unlisted' by default")
    print("   • You can change to 'public' in YouTube Studio")
    print("   • Or use update_video action to change privacy")
    print("   • Daily upload limit: 6 videos (default quota)")
    
    print("\n✨ All done!")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n⚠️  Workflow cancelled by user")
    except Exception as e:
        print(f"\n\n❌ Error: {e}")
        import traceback
        traceback.print_exc()
